slightly refactored the i3scrot script

diff --git a/.scripts/i3-scrot b/.scripts/i3-scrot
--- a/.scripts/i3-scrot
+++ b/.scripts/i3-scrot
@@ -1,80 +1,60 @@
 #!/bin/sh
-# /usr/bin/i3-scrot
 
 # simple screenshot-script using scrot for manjaro-i3 by oberon@manjaro.org
+# modified by me! @hcpsilva
 
-_conf=$HOME/.config/i3-scrot.conf
+DEFAULT_DIR=$HOME/Pictures
 
-if ! [ -f $_conf ]; then
-    echo "scrot_dir=$(xdg-user-dir PICTURES)" > $_conf
-fi
+usage() {
+cat <<EOF
+USAGE:
+  $0 [OPTIONS] [directory]
 
-. $_conf
+WHERE [OPTIONS] are:
+  -d | --desk    full screen
+  -w | --window  active window
+  -s | --select  selection
+  -h | --help    display this information
+
+Default option is 'full screen'.
+
+Default directory to save the images is $DEFAULT_DIR
+EOF
+}
+
+scrot_dir=${2:-$DEFAULT_DIR}
 
 if ! [ -d $scrot_dir ]; then
     mkdir -p $scrot_dir
 fi
 
-if ! [ -z "$2" ]; then
-    cmd="scrot -d $2"
-else
-    cmd='scrot'
-fi
-
-case "$1" in
-    --desk|-d|$NULL)
-        cd $scrot_dir
-        $cmd &&
-            sleep 1 &&
-            notify-send "screenshot has been saved in $scrot_dir"
-        ;;
-    --window|-w)
-        cd $scrot_dir
-        $cmd -u &&
-            sleep 1 &&
-            notify-send "screenshot has been saved in $scrot_dir"
-        ;;
-    --select|-s)
-        cd $scrot_dir
-        scrot -fs &&
-            sleep 1 &&
-            notify-send "screenshot has been saved in $scrot_dir"
-        ;;
-    --help|-h)
-        echo "
-available options:
--d | --desk    full screen
--w | --window  active window
--s | --select  selection
--h | --help    display this information
-
-The -d or -w options can be used with a delay
-by adding the number of seconds, like for example:
-'i3-scrot -w 5'
-
-Default option is 'full screen'.
-
-The file destination can be set in ${_conf}.
-Default is $scrot_dir
-"
-        ;;
-    *)
-        echo "
-== ! i3-scrot: missing or wrong argument ! ==
-
-available options:
--d | --desk    full screen
--w | --window  active window
--s | --select  selection
--h | --help    display this information
-
-Default option is 'full screen'.
-
-The file destination can be set in ${_conf}.
-Default is $scrot_dir
-"
-
-        exit 2
-esac
+for i in "$@"; do
+    case $i in
+        --desk|-d)
+            cd $scrot_dir
+            scrot &&
+                notify-send "screenshot has been saved in $scrot_dir"
+            ;;
+        --window|-w)
+            cd $scrot_dir
+            scrot -u &&
+                notify-send "screenshot has been saved in $scrot_dir"
+            ;;
+        --select|-s)
+            cd $scrot_dir
+            scrot -fs &&
+                notify-send "screenshot has been saved in $scrot_dir"
+            ;;
+        --help|-h)
+            usage
+            ;;
+        *)
+            echo "ERROR: Unknown argument '$i'"
+            echo
+            usage
+            exit 2
+            ;;
+    esac
+done
 
 exit 0
